package aufgabe1.a0;

public enum Fach {
	MATHEMATIKSTUDIUM, INFORMATIKSTUDIUM, ARCHITEKTURSTUDIUM, WIRTSCHAFTLICHESSTUDIUM, BIOLOGIESTUDIUM, GESCHICHTSSTUDIUM, GERMANISTIKSTUDIUM, POLITOLOGIESTUDIUM, PHYSIKSTUDIUM;
}
